n, *a = map(int, open("27-54b.txt").read().split())
max1 = sorted(filter(lambda x: x % 4 == 1, a))
max2 = sorted(filter(lambda x: x % 4 == 2, a))
max3 = sorted(filter(lambda x: x % 4 == 3, a))
max0 = sorted(filter(lambda x: x % 4 == 0, a))
print(max1[-4:])
print(max2[-4:])
print(max3[-4:])
print(max0[-4:])
